version: "2"
services:
  jupyter:
    build:
      context: src/
    command: jupyter-lab --ip=0.0.0.0 --port=8888    --NotebookApp.token='' --NotebookApp.iopub_data_rate_limit=20000000 --NotebookApp.notebook_dir='/code'
    volumes:
      - ./src/:/code
    ports:
      - 8882:8888
volumes:
  data:
