name: conda_env
channels:
- defaults
dependencies:
- python=3.5
- Jupyter
- Theano=1.0.2
- numpy=1.15
- scipy=1.1.0
- pandas=0.23.4
- matplotlib=3.0.0
- pip:
  - jupyterlab==0.35.4
  - jupyterthemes==0.20.0
  - sklearn
  - opencv-python
